name: Run tests, coverage, and publish to pages for main

on:
  push:
    branches: "main"

jobs:
  build-demo:
    uses: ./.github/workflows/build-demo-for-main.yml
    
  create-and-publish-coverage:
    needs: build-demo
    uses: ./.github/workflows/coverage-and-badge.yml
