name: Release workflow
run-name: Release workflow for ${{ github.ref_name }}

on:
  release:
    types: [published]

jobs:
  set_version_to_tag:
    uses: ./.github/workflows/set-version-to-tag.yml
    with:
      ref: ${{github.ref}}
      ref_name: ${{ github.ref_name }}

  point_tag_to_new_commit:
    needs: set_version_to_tag
    uses: ./.github/workflows/point-tag-to-new-commit.yml
    with:
      tag_name: ${{ github.ref_name }}
      commit_sha: ${{ needs.set_version_to_tag.outputs.merge_commit_sha }}
    secrets:
      REF_UPDATE_PAT: ${{ secrets.REF_UPDATE_PAT }}

  create-and-publish-coverage:
    needs: set_version_to_tag
    uses: ./.github/workflows/coverage-and-badge.yml
    with:
      ref: ${{ github.ref }}
