name: test sha update

on:         
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
        
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
    
env:
    GH_TOKEN: ${{ github.token }}
    
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Point a tag to a new commit
        run: |
          TAG=${{ inputs.tag_name }}
          COMMIT=${{ inputs.commit_sha }}
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ydernov/typing-effect/git/refs/tags/$TAG \
            -f sha="$COMMIT" \
           -F force=true 
