name: Publish package to GitHub Packages

on: 
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
        always-auth: true

    # Repo owner name in package.json name is mandatory for publishing to github packaages
    - name: Add scope to the name in package.json
      run: |
        # capture current name, then prepend owner name for scope
        sed -i 's/"name": "\(.*\)"/"name": "@ydernov\/\1"/' package.json
        npm i

    # Relative links to assets in reaadme e.g. GIF's, are not updated to absolutes, so they don't work on the package page
    # so we update them manually
    - name: Change links in readme
      run: |
        REPO_LINK=https://github.com/ydernov/typing-effect/raw/main/
        sed -i "s|\(\<img src\=\"\)\(example_demos\)|\1$REPO_LINK\2|" README.md
    
    - run: npm run build
    - run: npm publish

