name: Publish package to GitHub Packages

on: 
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: write
  
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
        always-auth: true

    - run: npm config list
      if: always()
      
    - run: cat /home/runner/work/_temp/.npmrc
      if: always()
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: ./*
        if-no-files-found: error
        retention-days: 1
        
    - run: npm ci
    - run: npm run build
    - run: npm publish

