name: test sha update

on:         
  workflow_dispatch:
    
    
env:
    GH_TOKEN: ${{ github.token }}
    
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:    
      
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commit and push changes
        run: |

          gh release edit 'v1.2.0' --target 4c998f5a777bcc66bafcda24df324ee3e1081d69


   
