name: test sha update 0

on:         
  workflow_dispatch:


env:
    GH_TOKEN: ${{ github.token }}

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:    


      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # fad7515f94e9f3aca39adfa923d6efcf523ae7f7

      - name: Commit and push changes
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ydernov/typing-effect/git/refs/tags/v1.2.0 \
            -f sha='fad7515f94e9f3aca39adfa923d6efcf523ae7f7' \
           -F force=true
           
          # gh release edit 'v1.2.0' --target 4c998f5a777bcc66bafcda24df324ee3e1081d69
