name: Update Version in package.json on Release

on:
 release:
    types: [published]
    
jobs:
 update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update package.json version
      run: |
        VERSION=${GITHUB_REF_NAME#v} # Remove the 'v' prefix
        echo "New version: $VERSION"
        sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout HEAD^
        git add package.json
        git commit -m "Update package.json version to $VERSION"
        git push

   
