name: Update Version in package.json on Release

on:
 release:
    types: [published]
    
jobs:
 update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update package.json version
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"

   
